// 26_Literal_Number_all.js

// JavaScript supports two numeric primitive types:
// 1. Number
// 2. BigInt

// 1. Number type
// The Number type is a double-precision 64-bit floating point value.
// It includes integers, decimals, and special numeric values.

// Decimal literal
const decimal = 42;
console.log('decimal:', decimal, 'type:', typeof decimal);

// Floating-point literal
const floatNum = 3.14;
console.log('floatNum:', floatNum, 'type:', typeof floatNum);

// Scientific notation
const scientific = 1.2e3; // 1200
console.log('scientific:', scientific, 'type:', typeof scientific);

// Binary literal (base 2)
const binary = 0b1010; // 10 in decimal
console.log('binary:', binary, 'type:', typeof binary);

// Octal literal (base 8)
const octal = 0o52; // 42 in decimal
console.log('octal:', octal, 'type:', typeof octal);

// Hexadecimal literal (base 16)
const hex = 0x2A; // 42 in decimal
console.log('hex:', hex, 'type:', typeof hex);

// Special Number values
const posInfinity = Infinity;
const negInfinity = -Infinity;
const notANumber = NaN;
console.log('Infinity:', posInfinity, 'type:', typeof posInfinity);
console.log('-Infinity:', negInfinity, 'type:', typeof negInfinity);
console.log('NaN:', notANumber, 'type:', typeof notANumber);

// 2. BigInt type
// BigInt is used for integers larger than Number.MAX_SAFE_INTEGER and for exact integer arithmetic.
const bigIntValue = 9007199254740993n; // Note the `n` suffix
console.log('bigIntValue:', bigIntValue, 'type:', typeof bigIntValue);

// BigInt arithmetic example
const bigA = 10n;
const bigB = 20n;
console.log('bigA + bigB =', bigA + bigB);

// Important: BigInt and Number are different types and do not mix directly.
const normalNumber = 10;
// The following line would throw a TypeError if uncommented:
// console.log('mixed add:', normalNumber + bigA);

// Use explicit conversion when combining Number and BigInt.
console.log('mixed add with conversion:', BigInt(normalNumber) + bigA);

// Summary of supported numeric systems in JavaScript:
// - Number: decimal, floating point, scientific notation
// - Number numeric literals in different bases: binary (0b), octal (0o), hexadecimal (0x)
// - Special Number values: Infinity, -Infinity, NaN
// - BigInt: integers with `n` suffix for arbitrary precision integer arithmetic

// The following data generated by opencode go kimi k2.6
// ============================================================
// Topic: All Number Types in JavaScript
// File: 26_Literal_Number_all.js
// ============================================================

/*
  In JavaScript, numbers are ALWAYS of type "number" (except BigInt).
  There is no separate int, float, double, etc.
  JS uses IEEE 754 double-precision 64-bit binary format.
*/


// --------------------------------------------------------
// 1. INTEGER LITERALS
// --------------------------------------------------------

// Decimal (Base 10) - most common
let decimal = 42;
console.log("Decimal:", decimal); // 42

// Binary (Base 2) - starts with 0b or 0B
let binary = 0b1010; // 10 in decimal
console.log("Binary 0b1010:", binary); // 10

// Octal (Base 8) - starts with 0o or 0O
let octal = 0o52; // 42 in decimal
console.log("Octal 0o52:", octal); // 42

// Hexadecimal (Base 16) - starts with 0x or 0X
let hex = 0x2A; // 42 in decimal
console.log("Hexadecimal 0x2A:", hex); // 42


// --------------------------------------------------------
// 2. FLOATING-POINT LITERALS
// --------------------------------------------------------

let float1 = 3.14;
let float2 = -0.5;
let float3 = .5;    // valid, but avoid for readability
let float4 = 5.;    // valid, but avoid for readability

console.log("Float 3.14:", float1);
console.log("Float -0.5:", float2);
console.log("Float .5:", float3);
console.log("Float 5.:", float4);

// Exponential notation
let exp1 = 1.5e3;   // 1.5 * 10^3 = 1500
let exp2 = 1.5e-3;  // 1.5 * 10^-3 = 0.0015
let exp3 = 2E10;    // 2 * 10^10 = 20000000000

console.log("Exponential 1.5e3:", exp1);   // 1500
console.log("Exponential 1.5e-3:", exp2);  // 0.0015
console.log("Exponential 2E10:", exp3);    // 20000000000


// --------------------------------------------------------
// 3. NUMERIC SEPARATORS (ES2021+)
// --------------------------------------------------------

let million = 1_000_000;
let binarySep = 0b1010_0001;
let hexSep = 0xFF_FF;

console.log("Separator 1_000_000:", million);      // 1000000
console.log("Separator 0b1010_0001:", binarySep);  // 161
console.log("Separator 0xFF_FF:", hexSep);         // 65535


// --------------------------------------------------------
// 4. BIGINT - For arbitrarily large integers
// --------------------------------------------------------

let big = 123456789012345678901234567890n;
let big2 = BigInt("123456789012345678901234567890");
let bigFromNum = BigInt(42);

console.log("BigInt literal:", big);
console.log("BigInt from string:", big2);
console.log("BigInt from number:", bigFromNum);
console.log("typeof BigInt:", typeof big); // "bigint"

// BigInt operations
console.log("BigInt + 1n:", big + 1n);
// Cannot mix BigInt with Number: 10n + 5 -> TypeError


// --------------------------------------------------------
// 5. SPECIAL NUMERIC VALUES
// --------------------------------------------------------

// Infinity
console.log("Infinity:", Infinity);           // Infinity
console.log("1 / 0:", 1 / 0);                 // Infinity
console.log("-1 / 0:", -1 / 0);               // -Infinity
console.log("typeof Infinity:", typeof Infinity); // "number"

// -Infinity
console.log("-Infinity:", -Infinity);

// NaN (Not a Number) - result of invalid math
console.log("NaN:", NaN);                     // NaN
console.log("0 / 0:", 0 / 0);                 // NaN
console.log("'hello' * 2:", "hello" * 2);     // NaN
console.log("typeof NaN:", typeof NaN);       // "number" (quirky!)




// --------------------------------------------------------
// 7. NUMBER PROPERTIES (Constants)
// --------------------------------------------------------

console.log("\n--- Number Properties ---");
console.log("MAX_VALUE:", Number.MAX_VALUE);             // ~1.79e308
console.log("MIN_VALUE:", Number.MIN_VALUE);             // ~5e-324
console.log("MAX_SAFE_INTEGER:", Number.MAX_SAFE_INTEGER); // 9007199254740991
console.log("MIN_SAFE_INTEGER:", Number.MIN_SAFE_INTEGER); // -9007199254740991
console.log("POSITIVE_INFINITY:", Number.POSITIVE_INFINITY);
console.log("NEGATIVE_INFINITY:", Number.NEGATIVE_INFINITY);
console.log("NaN property:", Number.NaN);
console.log("EPSILON:", Number.EPSILON);                 // smallest diff between 2 numbers


// --------------------------------------------------------
// 8. NUMBER METHODS
// --------------------------------------------------------


// --------------------------------------------------------
// SUMMARY TABLE
// --------------------------------------------------------

/*
  | Type/Form          | Example            | Notes                          |
  |--------------------|--------------------|--------------------------------|
  | Decimal Integer    | 42                 | Standard whole numbers         |
  | Binary             | 0b1010             | Base 2, starts with 0b         |
  | Octal              | 0o52               | Base 8, starts with 0o         |
  | Hexadecimal        | 0x2A               | Base 16, starts with 0x        |
  | Float              | 3.14               | Decimal numbers                |
  | Exponential        | 1.5e3              | Scientific notation            |
  | Numeric Separator  | 1_000_000          | ES2021+, for readability       |
  | BigInt             | 123n or BigInt(123)| Arbitrary large integers       |
  | Infinity           | Infinity           | Result of division by zero     |
  | NaN                | NaN                | Invalid numeric operation      |
  | Number Object      | new Number(42)     | Avoid, use primitive           |
*/


// ============================================================
// END
// ============================================================